In [1]:
import numpy as np
import pandas as pd

#  DataFrames

In [2]:
data = [
    ['Nissan', 'Stanza', 1991, 138, 4, 'MANUAL', 'sedan', 2000],
    ['Hyundai', 'Sonata', 2017, None, 4, 'AUTOMATIC', 'Sedan', 27150],
    ['Lotus', 'Elise', 2010, 218, 4, 'MANUAL', 'convertible', 54990],
    ['GMC', 'Acadia',  2017, 194, 4, 'AUTOMATIC', '4dr SUV', 34450],
    ['Nissan', 'Frontier', 2017, 261, 6, 'MANUAL', 'Pickup', 32340],
]

columns = [
    'Make', 'Model', 'Year', 'Engine HP', 'Engine Cylinders',
    'Transmission Type', 'Vehicle_Style', 'MSRP'
]

In [6]:
pd.DataFrame(data , columns =columns)  # Create a DataFrame with the specified data and column names

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [7]:
df = pd.DataFrame(data , columns =columns)  # Create a DataFrame with the specified data and column names

In [8]:
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [11]:
data = [
    {
        "Make": "Nissan",
        "Model": "Stanza",
        "Year": 1991,
        "Engine HP": 138.0,
        "Engine Cylinders": 4,
        "Transmission Type": "MANUAL",
        "Vehicle_Style": "sedan",
        "MSRP": 2000
    },
    {
        "Make": "Hyundai",
        "Model": "Sonata",
        "Year": 2017,
        "Engine HP": None,
        "Engine Cylinders": 4,
        "Transmission Type": "AUTOMATIC",
        "Vehicle_Style": "Sedan",
        "MSRP": 27150
    },
    {
        "Make": "Lotus",
        "Model": "Elise",
        "Year": 2010,
        "Engine HP": 218.0,
        "Engine Cylinders": 4,
        "Transmission Type": "MANUAL",
        "Vehicle_Style": "convertible",
        "MSRP": 54990
    },
    {
        "Make": "GMC",
        "Model": "Acadia",
        "Year": 2017,
        "Engine HP": 194.0,
        "Engine Cylinders": 4,
        "Transmission Type": "AUTOMATIC",
        "Vehicle_Style": "4dr SUV",
        "MSRP": 34450
    },
    {
        "Make": "Nissan",
        "Model": "Frontier",
        "Year": 2017,
        "Engine HP": 261.0,
        "Engine Cylinders": 6,
        "Transmission Type": "MANUAL",
        "Vehicle_Style": "Pickup",
        "MSRP": 32340
    }
]

In [12]:
pd.DataFrame(data)

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [ ]:
df.head()   # Display the first few rows of the DataFrame

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [15]:
df.head(2) # Display the first two rows of the DataFrame

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150

# Series

In [18]:
df.Make  # Access the 'Make' column of the DataFrame

0     Nissan
1    Hyundai
2      Lotus
3        GMC
4     Nissan
Name: Make, dtype: str

In [19]:
df["Transmission Type"]  # Access the 'Transmission Type' column of the DataFrame using bracket notation
# here we are accessing the 'Transmission Type' column of the DataFrame using bracket notation. 
#This is an alternative way to access columns in a DataFrame, and it allows us to use column names that contain spaces or special characters.

0       MANUAL
1    AUTOMATIC
2       MANUAL
3    AUTOMATIC
4       MANUAL
Name: Transmission Type, dtype: str

In [20]:
df[["Make", "Model", "Year"]]  # Access multiple columns of the DataFrame using a list of column names

      Make     Model  Year
0   Nissan    Stanza  1991
1  Hyundai    Sonata  2017
2    Lotus     Elise  2010
3      GMC    Acadia  2017
4   Nissan  Frontier  2017

In [32]:
df["id"] = [10, 20, 30, 40, 50]  # Add a new column 'id' to the DataFrame with specified values
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP,id
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000,10
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150,20
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990,30
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450,40
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340,50

In [33]:
del df["id"]  # Delete the 'id' column from the DataFrame
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

# Index

In [36]:
df.index # Access the index of the DataFrame

RangeIndex(start=0, stop=5, step=1)

In [38]:
df.Make.index     # Access the index of the 'Make' column of the DataFrame

RangeIndex(start=0, stop=5, step=1)

In [40]:
df.loc[1]   # Access the row at index 1 of the DataFrame using the .loc accessor

Make                   Hyundai
Model                   Sonata
Year                      2017
Engine HP                  NaN
Engine Cylinders             4
Transmission Type    AUTOMATIC
Vehicle_Style            Sedan
MSRP                     27150
Name: 1, dtype: object

In [44]:
df.loc[[1, 2]]   # Access multiple rows at indices 1 and 2 of the DataFrame using the .loc accessor

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990

In [46]:
df.index = ["a", "b", "c", "d", "e"]  # Set a custom index for the DataFrame
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
a,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
b,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
c,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
d,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
e,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [49]:
df.loc[["b", "c"]]  # Access rows with custom indices 'b' and 'c' of the DataFrame using the .loc accessor

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
b,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
c,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990

In [52]:
df.iloc[1]  # Access the row at position 1 of the DataFrame using the .iloc accessor 
            # indexing with .iloc is based on the integer position of the rows, regardless of the index labels.

Make                   Hyundai
Model                   Sonata
Year                      2017
Engine HP                  NaN
Engine Cylinders             4
Transmission Type    AUTOMATIC
Vehicle_Style            Sedan
MSRP                     27150
Name: b, dtype: object

In [57]:
df.iloc[[1, 2, 4]] # Access multiple rows at positions 1, 2, and 4 of the DataFrame using the .iloc accessor

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
b,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
c,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
e,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [61]:
df.reset_index()    # Reset the index of the DataFrame to the default integer index and return a new DataFrame.

,index,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,a,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,b,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,c,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,d,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,e,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [64]:
df.reset_index(drop=True)  
# Reset the index of the DataFrame to the default integer index, dropping the current index and returning a new DataFrame without the old index column.

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

# Element-Wise Operations

In [68]:
df["Engine HP"] / 100    # Divide the 'Engine HP' column of the DataFrame by 100, resulting in a new Series with the halved values of 'Engine HP'.

a    1.38
b     NaN
c    2.18
d    1.94
e    2.61
Name: Engine HP, dtype: float64

In [70]:
df["Engine Cylinders"] * 2  # Multiply the 'Engine Cylinders' column of the DataFrame by 2, resulting in a new Series with the doubled values of 'Engine Cylinders'.

a     8
b     8
c     8
d     8
e    12
Name: Engine Cylinders, dtype: int64

In [73]:
df["Engine HP"] > 200 # Create a boolean Series indicating whether each value in the 'Engine HP' column is greater than 200

a    False
b    False
c     True
d    False
e     True
Name: Engine HP, dtype: bool

# Filtering

In [75]:
df[df["Engine HP"] > 200]  # Filter the DataFrame to include only rows where the 'Engine HP' column is greater than 200

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
c,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
e,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [77]:
df[df["Make"] == "Toyota"]  # Filter the DataFrame to include only rows where the 'Make' column is equal to "Toyota"

Empty DataFrame
Columns: [Make, Model, Year, Engine HP, Engine Cylinders, Transmission Type, Vehicle_Style, MSRP]
Index: []

In [79]:
df[(df["Make"] == "Toyota") & (df["Engine HP"] > 200)]  
# Filter the DataFrame to include only rows where the 'Make' column is equal to "Toyota" and 'Engine HP' is greater than 200

Empty DataFrame
Columns: [Make, Model, Year, Engine HP, Engine Cylinders, Transmission Type, Vehicle_Style, MSRP]
Index: []

# String Operations

In [82]:
"STRr".lower() # Convert the string "STRr" to lowercase, resulting in "strr"

'strr'

In [84]:
df["Vehicle_Style"].str.lower()  # Convert all the strings in the 'Vehicle_Style' column of the DataFrame to lowercase

a          sedan
b          sedan
c    convertible
d        4dr suv
e         pickup
Name: Vehicle_Style, dtype: str

In [86]:
"Machine Learning Zoomcamp".replace(" ", "_") 
# Replace all spaces in the string "Machine Learning Zoomcamp" with underscores, resulting in "Machine_Learning_Zoomcamp"  
# syntax for the replace() method is: string.replace(old, new), where 'old' is the substring to be replaced and 'new' is the substring to replace it with.

'Machine_Learning_Zoomcamp'

In [ ]:
df["Vehicle_Style"].replace(" ", "_")  # Replace all spaces in the strings of the 'Vehicle_Style' column of the DataFrame with underscores
# remember that the replace will not chage the original DataFrame unless you assign it back to the column or use the inplace parameter.

a          sedan
b          Sedan
c    convertible
d        4dr SUV
e         Pickup
Name: Vehicle_Style, dtype: str

In [90]:
df["Vehicle_Style"] = df["Vehicle_Style"].replace(" ", "_")  
# Assign the modified 'Vehicle_Style' column back to the DataFrame, replacing spaces with underscores in the strings of that column.
df["Vehicle_Style"]

a          sedan
b          Sedan
c    convertible
d        4dr SUV
e         Pickup
Name: Vehicle_Style, dtype: str

# Summarizing operations

In [92]:
df.MSRP.max()   # Find the maximum value in the 'MSRP' column of the DataFrame

np.int64(54990)

In [94]:
df.MSRP.min()   # Find the minimum value in the 'MSRP' column of the DataFrame

np.int64(2000)

In [96]:
df.MSRP.mean() # Calculate the mean (average) value of the 'MSRP' column in the DataFrame

np.float64(30186.0)

In [ ]:
df.describe() # Generate descriptive statistics for the DataFrame, including count, mean, std, min, 25%, 50%, 75%, and max values for each numeric column.

              Year  Engine HP  Engine Cylinders          MSRP
count     5.000000    4.00000          5.000000      5.000000
mean   2010.400000  202.75000          4.400000  30186.000000
std      11.260551   51.29896          0.894427  18985.044904
min    1991.000000  138.00000          4.000000   2000.000000
25%    2010.000000  180.00000          4.000000  27150.000000
50%    2017.000000  206.00000          4.000000  32340.000000
75%    2017.000000  228.75000          4.000000  34450.000000
max    2017.000000  261.00000          6.000000  54990.000000

In [102]:
df.MSRP.describe().round(2) # Generate descriptive statistics for the 'MSRP' column of the DataFrame, rounding the results to 2 decimal places

# Generate descriptive statistics for the 'MSRP' column of the DataFrame, including count, mean, std, min, 25%, 50%, 75%, and max values.

count        5.00
mean     30186.00
std      18985.04
min       2000.00
25%      27150.00
50%      32340.00
75%      34450.00
max      54990.00
Name: MSRP, dtype: float64

In [104]:
df.nunique()  # Count the number of unique values in each column of the DataFrame

Make                 4
Model                5
Year                 3
Engine HP            4
Engine Cylinders     2
Transmission Type    2
Vehicle_Style        5
MSRP                 5
dtype: int64

In [103]:
df.Make.nunique()  # Count the number of unique values in the 'Make' column of the DataFrame

4

# Missing Value

In [106]:
df.isnull() 
# Check for missing values in the DataFrame, returning a DataFrame of the same shape with boolean values indicating whether each element is null (True) or not (False)

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
a,False,False,False,False,False,False,False,False
b,False,False,False,True,False,False,False,False
c,False,False,False,False,False,False,False,False
d,False,False,False,False,False,False,False,False
e,False,False,False,False,False,False,False,False

In [107]:
df.isnull().sum()  # Count the number of missing values in each column of the DataFrame, returning a Series with the counts for each column

Make                 0
Model                0
Year                 0
Engine HP            1
Engine Cylinders     0
Transmission Type    0
Vehicle_Style        0
MSRP                 0
dtype: int64

# Grouping

In [109]:
df.groupby("Transmission Type").MSRP.mean() 
# Group the DataFrame by the 'Transmission Type' column and calculate the mean of the 'MSRP' column for each group, returning a Series with the mean values for each transmission type.

Transmission Type
AUTOMATIC    30800.000000
MANUAL       29776.666667
Name: MSRP, dtype: float64

In [111]:
df.groupby("Transmission Type").MSRP.min()

Transmission Type
AUTOMATIC    27150
MANUAL        2000
Name: MSRP, dtype: int64

In [112]:
df.groupby("Transmission Type").MSRP.max()

Transmission Type
AUTOMATIC    34450
MANUAL       54990
Name: MSRP, dtype: int64

# Getting the Numpy Arrays

In [ ]:
df.MSRP.values
# Access the underlying numpy array of values in the 'MSRP' column of the DataFrame, returning a 1-dimensional array containing the values of that column.

array([ 2000, 27150, 54990, 34450, 32340])

In [ ]:
df.to_dict(orient="records")  
# Convert the DataFrame to a list of dictionaries, where each dictionary represents a row in the DataFrame with column names as keys and corresponding values as values.
#  The 'records' orientation means that each row is represented as a separate dictionary.

[{'Make': 'Nissan',
  'Model': 'Stanza',
  'Year': 1991,
  'Engine HP': 138.0,
  'Engine Cylinders': 4,
  'Transmission Type': 'MANUAL',
  'Vehicle_Style': 'sedan',
  'MSRP': 2000},
 {'Make': 'Hyundai',
  'Model': 'Sonata',
  'Year': 2017,
  'Engine HP': nan,
  'Engine Cylinders': 4,
  'Transmission Type': 'AUTOMATIC',
  'Vehicle_Style': 'Sedan',
  'MSRP': 27150},
 {'Make': 'Lotus',
  'Model': 'Elise',
  'Year': 2010,
  'Engine HP': 218.0,
  'Engine Cylinders': 4,
  'Transmission Type': 'MANUAL',
  'Vehicle_Style': 'convertible',
  'MSRP': 54990},
 {'Make': 'GMC',
  'Model': 'Acadia',
  'Year': 2017,
  'Engine HP': 194.0,
  'Engine Cylinders': 4,
  'Transmission Type': 'AUTOMATIC',
  'Vehicle_Style': '4dr SUV',
  'MSRP': 34450},
 {'Make': 'Nissan',
  'Model': 'Frontier',
  'Year': 2017,
  'Engine HP': 261.0,
  'Engine Cylinders': 6,
  'Transmission Type': 'MANUAL',
  'Vehicle_Style': 'Pickup',
  'MSRP': 32340}]